### ISSUE TITLE
Failing while installing with chicago boss

### ISSUE THREAD

**Issue by jigs2410** [basho/riak_pb#124]
==> riak_pb (compile)
/home/erlangdeveloper/ChicagoBoss/deps/riak_pb/src/riak_pb_kv_codec.erl:52: type dict() undefined
ERROR: compile failed while processing /home/erlangdeveloper/ChicagoBoss/deps/riak_pb: rebar_abort
make: *** [erl_compile] Error 1

When i try to install this separately its failing too

sudo make
==> meck (get-deps)
==> protobuffs (get-deps)
==> riak_pb (get-deps)
==> meck (pre_compile)
==> meck (compile)
==> protobuffs (pre_compile)
==> protobuffs (compile)
==> riak_pb (pre_compile)
Generated src/riak_pb_messages.erl
==> riak_pb (compile)
Compiling src/riak_dt.proto

=INFO REPORT==== 30-Jun-2015::03:09:29 ===
Writing header file to "riak_dt_pb.hrl"
ERROR: compile failed while processing /home/erlangdeveloper/riak_pb: {'EXIT',
    {{badmatch,
         {error,[],
             [{"src/riak_dt_pb.erl",
               [{244,erl_lint,{exported_var,'FNum',{'case',226}}}]}]}},
     [{protobuffs_compile,output,4,
          [{file,"src/protobuffs_compile.erl"},{line,147}]},
      {rebar_protobuffs_compiler,compile_each,2,
          [{file,"src/rebar_protobuffs_compiler.erl"},{line,111}]},
      {rebar_core,run_modules,4,[{file,"src/rebar_core.erl"},{line,491}]},
      {rebar_core,execute,6,[{file,"src/rebar_core.erl"},{line,416}]},
      {rebar_core,maybe_execute,8,[{file,"src/rebar_core.erl"},{line,300}]},
      {rebar_core,process_dir1,7,[{file,"src/rebar_core.erl"},{line,259}]},
      {rebar_core,process_commands,2,[{file,"src/rebar_core.erl"},{line,91}]},
      {rebar,main,1,[{file,"src/rebar.erl"},{line,58}]}]}}
make: *** [erl_compile] Error 1

I am on ubuntu using OTP release 18

**Comment by mrallen1** [comment]
OTP 18 is not supported and we've not even tested builds on it yet.  You'll have to use a less recent OTP release.  I strongly recommend using the Basho supplied OTP if you're planning to run Riak in production.  https://github.com/basho/otp

**Comment by jigs2410** [comment]
Ok thanks i rolled to OTP version R16B01 and chicago boss got installed without complaints.

**Comment by mrallen1** [comment]
I would still recommend using Basho's OTP distribution (R16B02_basho8). In particular, the R16B01 release has a pretty serious bug relating to process monitors being mishandled by the run-time system.

**Comment by mremond** [comment]
This issue should be fixed by this PR: https://github.com/basho/erlang_protobuffs/pull/88
