### ISSUE TITLE
erlang 18.0 compatibility: type dict() undefined

### ISSUE THREAD

**Issue by p5n** [basho/riak_pb#128]
making this project as ejabberd dependency produces

ejabberd-15.06/deps/riak_pb/src/riak_pb_kv_codec.erl:52: type dict() undefined

**Comment by allran** [comment]
I have the same issue, please edit it, thanks.

**Comment by FlowerWrong** [comment]
+1

**Comment by android-programmer** [comment]
+1

**Comment by p5n** [comment]
need to be replaced to dict:dict() probably.

**Comment by jesuisbonbon** [comment]
did someone managed to make this lib work on OPT18?

**Comment by lukebakken** [comment]
Fixed by c6aa6000770ef6bd4fba7c8e0b83351d608902f0
