### ISSUE TITLE
rebar3 builds [JIRA: RIAK-2756]

### ISSUE THREAD

**Issue by paulperegud** [basho/riak_pb#180]
It would be great to be able to build riak_pb with rebar3. 

One element which is missing and requires more work is a protoc plugin for rebar3 which uses basho/erlang_protobuffs. There is lrascao/rebar3_gpb_plugin but unfortunately it uses gpb.

**Comment by lucafavatella** [comment]
There are two rebar3 protobuf plugins using basho/erlang_protobuffs - see https://github.com/basho/rebar3_protobuf_plugin/issues/1

**Comment by lukebakken** [comment]
@paulperegud -

As of PR #197, `riak_pb` no longer requires a plugin to build. The files generated from the `.proto` files are committed to the repository. As a bonus, we have switched to the `gpb` protobuf library.

This change will be part of the next `riak_pb` release, but can be used now if you use the `develop` branch.
