### ISSUE TITLE
(Mix) Could not compile dependency :riak_pb [JIRA: RIAK-3229]

### ISSUE THREAD

**Issue by churcho** [basho/riak_pb#221]
I am getting an error when I try to run my elixir app which uses riak_pb as a dependency to [riak-erlang-client](https://github.com/basho/riak-erlang-client)

The error is 
<code>
** (Mix) Could not compile dependency :riak_pb, "/Users/myuser/.mix/rebar3 bare compile --paths "/Users/myuser/app_backend/_build/dev/lib/*/ebin"" command failed. You can recompile this dependency with "mix deps.compile riak_pb", update it with "mix deps.update riak_pb" or clean it with "mix deps.clean riak_pb"
</code>

**Comment by lukebakken** [comment]
* Can you please provide complete source to reproduce this issue?
* What happens when you follow the instructions given?
    > You can recompile this dependency with "mix deps.compile riak_pb", update it with "mix deps.update riak_pb" or clean it with "mix deps.clean riak_pb"

**Comment by churcho** [comment]
I resolved it by changing my mix setting from <code> {:riakc, github: "basho/riak-erlang-client", manager: :rebar3}</code> to <code> {:riakc, github: "basho/riak-erlang-client"}</code> and it seems to be working fine now.

**Comment by lukebakken** [comment]
Great, thank you for the information.
