### ISSUE TITLE
Unable to run test-suite in Ubuntu 18.04

### ISSUE THREAD

**Issue by mathiasertl** [basho/riak_pb#225]
When trying to run the test-suite on Ubuntu 18.04, I get the following error:

```
root@pallene:/home/mati/repositories/erlang-riak-protobuf# make test
==> meck (pre_compile)
==> meck (compile)
==> protobuffs (pre_compile)
==> protobuffs (compile)
==> hamcrest (pre_compile)
==> hamcrest (compile)
==> hamcrest (post_compile)
==> erlang-riak-protobuf (pre_compile)
==> erlang-riak-protobuf (compile)
./rebar eunit skip_deps=true
==> erlang-riak-protobuf (eunit)
src/riak_pb_codec.erl:33: export_all flag enabled - all functions will be exported
Compiling src/riak_pb_codec.erl failed:
ERROR: eunit failed while processing /home/mati/repositories/erlang-riak-protobuf: rebar_abort
tools.mk:38: recipe for target 'test' failed
make: *** [test] Error 1
```

I have installed the following dependencies - and ``make`` runs fine as well:

```
apt-get install debhelper  dpkg-dev  erlang-dev erlang-parsetools dh-rebar erlang-syntax-tools erlang-eunit git ca-certificates
```

**Comment by russelldb** [comment]
Hi, thanks for the report. Do you know which version of erlang you're running?
Is this on branch `develop`?

**Comment by mathiasertl** [comment]
Hi,

I used the 2.3.2 tag. 

Ubuntu 18.04 currently has 20.1.7 (see [package search](https://packages.ubuntu.com/search?keywords=erlang&searchon=names&exact=1&suite=bionic&section=all)

**Comment by mathiasertl** [comment]
Apologies - turns out my previous comment was wrong. 

I used 2.1.4.2, because that is what the current Debian package is using. I will update the version and file a new ticket if the issue persists.

**Comment by russelldb** [comment]
Looks like an erlang 20 thing. It's a new warning, it can be disabled. Riak is still stuck on OTP r16, I don't know if this library is supposed to be supported on a later erlang.

As part of getting this ready for erlang 20 we'll have to address that warning, maybe in the rebar.config?
