### ISSUE TITLE
Discussion: Go Import

### ISSUE THREAD

**Issue by boj** [basho/riak_pb#71]
Conversation started by @seancribbs with @mrb and myself.  https://twitter.com/seancribbs/status/411177656088924160 - The general idea is to allow [Go](http://golang.org) to directly import this project via it's import mechanism.

The potential problem here is that the generated Go files would have to exist inside this project and maintained by somebody, there is no straightforward way for the Go import system to automate it.

Go's import system is namespaced by literal project paths.  When one issues the command `go get some/project` the library is stored in the local `$GOPATH` and becomes available to the developer.

    package mylib

    import "github.com/basho/riak_pb/gorpb" // gorpb is now available

    func main() {
        foo := gorpb.RpbFoo{
           Bar: []byte("Baz"),
        }
        // Do stuff with foo
    }

Including the files at the top level creates a bit of project noise, so the example above uses a sub directory which serves as the *.go file location and project import path/name.

The *.go files for projects that currently use riak_pb are built with [goprotobuf](https://code.google.com/p/goprotobuf/).

**Comment by lukebakken** [comment]
Please look at how the Riak Go Client uses this repository:

https://github.com/basho/riak-go-client

* `riak_pb` is set up as a submodule.
* [`build/protogen`](https://github.com/basho/riak-go-client/blob/master/build/protogen) is used to re-generate the files in the `rpb/` directory.
* Generated files are then committed.
