### ISSUE TITLE
riak_pb_messages.beam does not get built with a current rebar version [JIRA: RIAK-1555]

### ISSUE THREAD

**Issue by hanikesn** [basho/riak_pb#95]
Try cloning the riak_pb repo two times. The first time build it with the included rebar binary, the second time build it with the rebar executable from https://raw.github.com/wiki/rebar/rebar/rebar.

The second time riak_pb_messages.beam does not get build, because the riak_pb_msgcodegen plugin is not used correctly.

This could also be an issue with rebar itself.

**Comment by DeadZen** [comment]
+1 get this thing merged in before it bit rots any further...

**Comment by Basho-JIRA** [comment]
[~seancribbs] please review and assign according to what you find out. 

***[posted via JIRA by Derek Somogyi]***

**Comment by DeadZen** [comment]
w00t

**Comment by cmeiklejohn** [comment]
I've merged these changes into #110 to have a resolved build.  I suggest we merge #110 and close this PR.

**Comment by seancribbs** [comment]
This was resolved by #110.
